# Generated by Django 5.2.4 on 2025-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_materials", "0002_course_created_at_course_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата изменения"
            ),
        ),
    ]
